name: Compile traceloop
on:
  push:
  schedule:
    - cron: '0 2 * * *' # Night builds at 02:00

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build traceloop
      # We need to download arm64 cross compiler before building binary.
      run: |
        sudo apt-get update
        sudo apt-get install -qy gcc-aarch64-linux-gnu
        make all

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      if: github.ref == 'refs/heads/main'

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      if: github.ref == 'refs/heads/main'

    - name: Login to Container Registry
      uses: docker/login-action@v1
      if: github.ref == 'refs/heads/main'
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cross build gadget container for amd64 and arm64.
      uses: docker/build-push-action@v2
      # We cross build only when pushing to main because it takes a lot of time.
      if: github.ref == 'refs/heads/main'
      with:
        context: .
        file: traceloop.Dockerfile
        push: true
        tags: kinvolk/traceloop:${{ github.sha }}
        # For the moment, we only support these two platforms.
        platforms: linux/amd64,linux/arm64

    - name: Build container and publish to Registry
      id: publish-registry
      uses: elgohr/Publish-Docker-Github-Action@2.8
      if: github.ref != 'refs/heads/main'
      with:
        name: docker.io/kinvolk/traceloop
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: .
        dockerfile: traceloop.Dockerfile
        snapshot: true
        cache: ${{ github.event_name != 'schedule' }}
